cache:
  paths:
    - .m2/repository
    - target 
    - node_module

stages: 
  - compile
  - test

compile-java:
  image: maven:latest
  stage: compile
  script: 
    - mvn clean install -DskipTest

test-java:
  image: maven:latest
  stage: test 
  script: 
    - mvn test

compile-javascript:
  image: node:latest
  stage: compile
  script: 
    - cd jsproject
    - npm i 
    - npm run build

test-javascript:
  image: node:latest
  stage: test
  script: 
    - cd jsproject
    - npm run test

