cache:
  paths:
    - .m2/repository
    - target 
    - node_module

stages: 
  - compile
  - test

compile-java:
  image: maven:latest
  stage: compile
  script: 
    - mvn clean install -DskipTest

test-java:
  image: maven:latest
  stage: test 
  script: 
    - mvn test
