#File : cloudbuild.yaml
steps:
  - name: 'maven'
    args: [ 'mvn', 'clean', 'install', '-DskipTest']
  - name: 'maven'
    args: ['mvn', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', 'deadl0ckk', '-p', '8f09be9e-477e-4cfd-ad9c-e80db98deb0f']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'deadl0ckk/cicd', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'deadl0ckk/cicd']
  - name: 'ubuntu'
    args: [ 'cd', 'jsproject']
  - name: 'node'
    args: ['npm', 'i', '&&', 'run', 'build']
  - name: 'npm'
    args: ['npm', 'run', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', 'deadl0ckk', '-p', '8f09be9e-477e-4cfd-ad9c-e80db98deb0f']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'deadl0ckk/cicd', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'deadl0ckk/cicd']
